/*data của admin giao diện website*/
export const slides = [
  {
    Id: 1,
    Title: 'React JS',
    ingredients: 'Tổng Hợp Thư Viện Tích Hợp',
    photoName: '/images/banner1.png',
  },
  {
    Id: 2,
    Title: 'Python',
    ingredients: 'Bread with italian olive oil and rosemary',
    photoName: '/images/banner2.png',
  },
  {
    Id: 3,
    Title: 'Focaccia',
    ingredients: 'Bread with italian olive oil and rosemary',
    photoName: '/images/banner3.png',
  },
]

export const navmenu = [
  {
    Id: 1,
    Name: 'Home',
    Url: '/Home',
    Item1: '',
    UrlItem1: '',
    Item2: '',
    UrlItem2: '',
    Item3: '',
    UrlItem3: '',
  },
  {
    Id: 2,
    Name: 'App',
    Url: ' ',
    Item1: 'For Android',
    UrlItem1: '',
    Item2: 'For Ios',
    UrlItem2: '',
    Item3: 'For Window/Mac',
    UrlItem3: '',
  },
  {
    Id: 3,
    Name: 'Library',
    Url: ' ',
    Item1: '',
    UrlItem1: '',
    Item2: '',
    UrlItem2: '',
    Item3: '',
    UrlItem3: '',
  },
  {
    Id: 4,
    Name: 'Shopping',
    Url: ' ',
    Item1: '',
    UrlItem1: '',
    Item2: '',
    UrlItem2: '',
    Item3: '',
    UrlItem3: '',
  },
  {
    Id: 5,
    Name: 'Contact',
    Url: '/pages/contacts ',
    Item1: '',
    UrlItem1: '',
    Item2: '',
    UrlItem2: '',
    Item3: '',
    UrlItem3: '',
  },
]

/*chỉ khi người dùng đạt thành tích sẽ kết nối tới data này để điền thông tin và vinh danh*/
export const rating = [
  {
    Id_rating: 1,
    Name: 'Adam',
    trendingArticles: 'Tổng Hợp Thư Viện Tích Hợp',
    content:
      'We use an agile approach to test assumptions and connect with the needs of your audience early and often.',
    Avatar: '/images/avatar2.avif',
    BlogImage: '/images/avatar2.avif',
    Label: true,
    date: '20/11/2024',
  },
  {
    Id_rating: 2,
    Name: 'Peter',
    trendingArticles: 'Bread with italian olive oil and rosemary',
    content: 'đây là ......',
    Avatar: '/images/avatar2.avif',
    Label: false,
    date: '20/11/2024',
  },
  {
    Id_rating: 3,
    Name: 'Focaccia',
    trendingArticles: 'Bread with italian olive oil and rosemary',
    content: 'đây là ......',
    Avatar: '/images/avatar3.avif',
    Label: false,
    date: '20/11/2024',
  },
  {
    Id_rating: 4,
    Name: 'Focaccia',
    trendingArticles: 'Bread with italian olive oil and rosemary',
    content: 'đây là ......',
    Avatar: '/images/avatar4.avif',
    Label: false,
    date: '20/11/2024',
  },
  {
    Id_rating: 5,
    Name: 'Focaccia',
    trendingArticles: 'Bread with italian olive oil and rosemary',
    content: 'đây là ......',
    Avatar: '/images/avatar4.avif',
    Label: false,
    date: '20/11/2024',
  },

  {
    Id_rating: 6,
    Name: 'Focaccia',
    trendingArticles: 'Bread with italian olive oil and rosemary',
    content: 'đây là ......',
    Avatar: '/images/avatar4.avif',
    Label: false,
    date: '20/11/2024',
  },
  {
    Id_rating: 7,
    Name: 'Focaccia333',
    trendingArticles: 'Bread with italian olive oil and rosemary',
    content: 'đây là ......',
    Avatar: '/images/avatar4.avif',
    Label: false,
    date: '20/11/2024',
  },
  {
    Id_rating: 8,
    Name: 'Focaccia',
    trendingArticles: 'Bread with italian olive oil and rosemary',
    content: 'đây là ......',
    Avatar: '/images/avatar4.avif',
    Label: false,
  },
  {
    Id_rating: 9,
    Name: 'Focaccia',
    trendingArticles: 'Bread with italian olive oil and rosemary',
    content: 'đây là ......',
    Avatar: '/images/avatar4.avif',
    Label: false,
    date: '20/11/2024',
  },
  {
    Id_rating: 10,
    Name: 'Focaccia',
    trendingArticles: 'Bread with italian olive oil and rosemary',
    content: 'đây là ......',
    Avatar: '/images/avatar4.avif',
    Label: false,
    date: '20/11/2024',
  },
]

export const userStorage = [
  {
    Id_Storage: 1,
    Label: 'Tutorial',
    Image: '',
    Title: '1Basic CSS Module',
    Content:
      '1Static websites are now used to bootstrap lots of websites and are becoming the basis for a variety of tools that even influence both web designers and developers influence both web designers and developers.',
    DateTime: '',
    Viewer: 6,
    Id_Rating: 1,
    Id_User: 1,
  },
  {
    Id_Storage: 2,
    Label: 'Book',
    Image: '',
    Title: '2Basic CSS Module',
    Content:
      '2Static websites are now used to bootstrap lots of websites and are becoming the basis for a variety of tools that even influence both web designers and developers influence both web designers and developers.',
    DateTime: '',
    Viewer: 5,
    Id_Rating: 1,
    Id_User: 1,
  },
  {
    Id_Storage: 3,
    Label: 'Book3',
    Image: '',
    Title: '3Basic CSS Module',
    Content:
      '2Static websites are now used to bootstrap lots of websites and are becoming the basis for a variety of tools that even influence both web designers and developers influence both web designers and developers.',
    DateTime: '',
    Viewer: 7,
    Id_Rating: 2,
    Id_User: 2,
  },
  {
    Id_Storage: 4,
    Label: 'Book3',
    Image: '',
    Title: '3Basic CSS Module',
    Content:
      '2Static websites are now used to bootstrap lots of websites and are becoming the basis for a variety of tools that even influence both web designers and developers influence both web designers and developers.',
    DateTime: '',
    Viewer: 9,
    Id_Rating: 2,
    Id_User: 2,
  },
]

export const User = [
  {
    Id_User: 1,
    Name: 'Adam',
    Avatar: '/images/avatar2.avif',
    Follower: 4,
    Viewerprofile: 2,
    Experient: 'Best React',
    Message: 'Hello All',
    Date_of_birth: '14/10/2004',
    GoogleDrive: 'abc',
    Id_rating: null,
    Id_Storage: 1,
  },

  {
    Id_User: 2,
    Name: 'Adam',
    Avatar: '/images/avatar2.avif',
    Follower: 4,
    Viewerprofile: 2,
    Experient: 'Best React',
    Message: 'Hello All',
    Date_of_birth: '14/10/2004',
    GoogleDrive: 'abc',
    Id_rating: null,
    Id_Storage: 3,
  },
]
